# Use a imagem base oficial do Python
FROM python:3.12.5-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copie os arquivos de dependências para o container
COPY requirements.txt .

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copie todo o conteúdo do projeto para o diretório de trabalho
COPY . .

# Exponha a porta da aplicação
EXPOSE 8000

# Comando para iniciar a aplicação FastAPI
CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000"]
